/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */


plugins {
    id("tf.veriny.gradle.base-plugin").version("0.7.1")
    id("fabric-loom").version("1.4.1")
}

group = "tf.veriny.unova"
version = "0.7.0"

loom.runs.named("client") {
    isIdeConfigGenerated = true
    programArgs("--mimicPlayer", project.properties["fabricMimicPlayer"].toString())
}

dependencies {
    "minecraft"("com.mojang:minecraft:1.20.1")

    // this odd mappings layout means we use QM names for everything, and yarn JD.
    mappings(loom.layered {
        mappings("net.fabricmc:yarn:1.20.1+build.10:v2")
        mappings("org.quiltmc:quilt-mappings:1.20.1+build.23:intermediary-v2")
    })

    // for configs
    api(include("cc.ekblad:4koma:1.2.0")!!)
    runtimeOnly(include("cc.ekblad.konbini:konbini-jvm:0.1.3")!!)

    modImplementation("net.fabricmc:fabric-loader:0.14.22")
    modImplementation("net.fabricmc.fabric-api:fabric-api:0.88.1+1.20.1")
    modImplementation("net.fabricmc:fabric-language-kotlin:1.10.10+kotlin.1.9.10")

    modApi("io.wispforest:owo-lib:0.11.2-pre.14+1.20") {
        exclude(group = "net.fabricmc.fabric-api")
    }

    modApi("dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.2")
    modApi("dev.onyxstudios.cardinal-components-api:cardinal-components-level:5.2.2")
    modApi("dev.onyxstudios.cardinal-components-api:cardinal-components-world:5.2.2")
    modApi("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.2")
    modApi("dev.onyxstudios.cardinal-components-api:cardinal-components-chunk:5.2.2")

    modLocalRuntime("com.ptsmods:devlogin:3.3.2")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])

            pom {
                name.set(project.name)
                description.set("+1 atk +1 def +1 spe")
                licenses {
                    license {
                        name.set("MPL-2.0")
                        url.set("https://www.mozilla.org/en-US/MPL/2.0/")
                    }
                }

                developers {
                    developer {
                        id.set("Fuyukai")
                        name.set("Lura Skye")
                        url.set("https://veriny.tf")
                    }
                }
            }
        }
    }
}