/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */


plugins {
    kotlin("jvm").version("2.0.0")
    id("maven-publish")
    id("com.github.ben-manes.versions").version("0.51.0")
    id("fabric-loom").version("1.5.7")
    id("com.palantir.git-version").version("3.1.0")
}

repositories {
    mavenCentral()
    maven("https://maven.quiltmc.org/repository/release/")
    maven("https://jitpack.io")
}

group = "tf.veriny.unova"
val gitVersion: groovy.lang.Closure<String> by extra
version = gitVersion().drop(1)  // we tag with v0.7.x

loom.runs.named("client") {
    isIdeConfigGenerated = true
    programArgs("--mimicPlayer", project.properties["fabricMimicPlayer"].toString())
}

kotlin {
    explicitApi()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))

    "minecraft"("com.mojang:minecraft:1.20.1")

    // this odd mappings layout means we use QM names for everything, and yarn JD.
    mappings(loom.layered {
        mappings("net.fabricmc:yarn:1.20.1+build.10:v2")
        mappings("org.quiltmc:quilt-mappings:1.20.1+build.23:intermediary-v2")
    })

    // for configs
    api(include("cc.ekblad:4koma:1.2.0")!!)
    runtimeOnly(include("cc.ekblad.konbini:konbini-jvm:0.1.3")!!)

    modImplementation("net.fabricmc:fabric-loader:0.14.22")
    modImplementation("net.fabricmc.fabric-api:fabric-api:0.90.0+1.20.1")
    modImplementation("net.fabricmc:fabric-language-kotlin:1.10.17+kotlin.1.9.22")

    modLocalRuntime("com.ptsmods:devlogin:3.5")
}

tasks.named<ProcessResources>("processResources") {
    inputs.property("version") { project.version }
    filesMatching("fabric.mod.json") { expand("version" to project.version) }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])

            pom {
                name.set(project.name)
                description.set("+1 atk +1 def +1 spe")
                licenses {
                    license {
                        name.set("MPL-2.0")
                        url.set("https://www.mozilla.org/en-US/MPL/2.0/")
                    }
                }

                developers {
                    developer {
                        id.set("Fuyukai")
                        name.set("Lura Skye")
                        url.set("https://veriny.tf")
                    }
                }
            }
        }
    }
}